CORE/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pet.urls')),
    path('', lambda request: redirect('pets:home')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pet/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'pets'

urlpatterns = [
    # pets
    path('pets/', views.home, name='home'),
    path('pets/my_pets/', views.my_pets, name='my_pets'),
    path('pet/<int:pet_id>/', views.pet_details, name='pet_detail'),
    path('pet/add/', views.add_pet, name='add_pet'),
    path('pet/my_adoptions/', views.my_adoptions, name='my_adoptions'),
    path('pet/edit/<int:pet_id>/', views.edit_pet, name='edit_pet'),
    path('pet/delete/<int:pet_id>/', views.delete_pet, name='delete_pet'),
    path('pet/schedule/<int:pet_id>/', views.schedule, name='schedule'),
    path('pet/confirm_adoption/<int:pet_id>/',
         views.confirm_adoption, name='confirm_adoption'),
    path('pet/refuse_adoption/<int:pet_id>/',
         views.refuse_adoption, name='refuse_adoption'),
    path('pet/search/<str:type>/',
         views.search_type, name='search'),

    # user
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('perfil/', views.profile, name='profile')
]

templates/partials/_footer.html
<footer class='footer'>
    <p>
       <span class='bold'>Get A Pet</span> &copy; 2024
    </p>
</footer>

templates/partials/_header.html
{% load static %}
<header class='navbar'>
    <a href="{% url "pets:home" %}">
        <div class="navbar_logo">
            <img src="{% static "imgs/cat.png" %}" alt="Logo">
            <h2>Get A Pet</h2>
        </div>
    </a>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url "pets:home" %}">Home</a></li>
            <li><a href="{% url "pets:my_adoptions" %}">Minhas Adoções</a></li>
            <li><a href="{% url "pets:my_pets" %}">Meus Pets</a></li>
            <li><a href="{% url "pets:profile" %}">Perfil</a></li>
            <li><a href="{% url "pets:logout" %}">Sair</a></li>
        {% else %}
            <li><a href="{% url "pets:home" %}">Home</a></li>
            <li><a href="{% url "pets:login" %}">Login</a></li>
            <li><a href="{% url "pets:register" %}">Cadastrar</a></li>
        {% endif %}
    </ul>

</header>

templates/partials/_messages.html
{% load static %}
{% block page_css %}
    <link rel="stylesheet" href="{% static "css/messages.css" %}">
{% endblock page_css %}

{% if messages %}
{% for message in messages %}
    <div class="message {{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}