CORE/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pet.urls')),
    path('', lambda request: redirect('pets:home')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pet/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'pets'

urlpatterns = [
    # pets
    path('pets/', views.home, name='home'),
    path('pets/my_pets/', views.my_pets, name='my_pets'),
    path('pet/<int:pet_id>/', views.pet_details, name='pet_detail'),
    path('pet/add/', views.add_pet, name='add_pet'),
    path('pet/my_adoptions/', views.my_adoptions, name='my_adoptions'),
    path('pet/edit/<int:pet_id>/', views.edit_pet, name='edit_pet'),
    path('pet/delete/<int:pet_id>/', views.delete_pet, name='delete_pet'),
    path('pet/schedule/<int:pet_id>/', views.schedule, name='schedule'),
    path('pet/confirm_adoption/<int:pet_id>/',
         views.confirm_adoption, name='confirm_adoption'),
    path('pet/refuse_adoption/<int:pet_id>/',
         views.refuse_adoption, name='refuse_adoption'),
    path('pet/search/<str:type>/',
         views.search_type, name='search'),

    # user
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('perfil/', views.profile, name='profile')
]

pet/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from datetime import date


class Pet(models.Model):

    name = models.CharField(max_length=80)

    COLOR_CHOICES = [
        ('white', 'Branco'),
        ('black', 'Preto'),
        ('yellow', 'Amarelo'),
        ('tricolor', 'Tricolor'),
        ('white_yellow', 'Branco e Amarelo'),
        ('black_white', 'Preto e Branco'),
    ]
    color = models.CharField(
        max_length=16,
        choices=COLOR_CHOICES,
        default=COLOR_CHOICES[0][0]
    )

    age = models.IntegerField(
        validators=[
            MinValueValidator(0)
        ]
    )

    AGE_CHOICES = [
        ('days', 'Dias'),
        ('months', 'Meses'),
        ('years', 'Anos'),
    ]
    age_type = models.CharField(
        max_length=6,
        choices=AGE_CHOICES,
        default=AGE_CHOICES[0][0]
    )

    TYPE_CHOICES = [
        ('cat', 'Gato'),
        ('dog', 'Cachorro'),
        ('hamster', 'Hamster'),
        ('rabbit', 'Coelho'),
    ]

    animal_type = models.CharField(
        max_length=8,
        choices=TYPE_CHOICES,
        default=TYPE_CHOICES[0][0]
    )

    available = models.BooleanField(default=True)

    created_at = models.DateField(default=date.today)
    owner = models.ForeignKey(
        User,
        related_name='owned_pets',
        on_delete=models.CASCADE
    )
    adopter = models.ForeignKey(
        User,
        related_name='adopted_pets',
        default=None,
        null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name


class PetImages(models.Model):
    picture = models.ImageField(
        upload_to='pet_imgs/%Y'
    )

    pet = models.ForeignKey(
        Pet,
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = 'Pet Images'

    def __str__(self):
        return f'Imagem pet - {self.pet}'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(
        upload_to='user_imgs/%Y', blank=True, null=True)
    phone = models.CharField(max_length=80, blank=True, null=True)

pet/forms.py
import re
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django import forms
from pet.models import Pet, UserProfile


class RegisterUser(UserCreationForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(RegisterUser, self).__init__(*args, **kwargs)

    first_name = forms.CharField(
        required=True,
        min_length=3
    )

    last_name = forms.CharField(
        required=True,
        min_length=3
    )

    email = forms.EmailField(
        required=True,
        min_length=3
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data["email"]
        stored_email = User.objects.filter(email=email)

        logged_user = self.request.user if self.request else None

        if stored_email and logged_user and logged_user.email != email:
            self.add_error(
                'email',
                ValidationError('esse email já existe escolha outro.')
            )

        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        stored_username = User.objects.filter(username=username)
        logged_user = self.request.user if self.request else None

        if stored_username and logged_user.username != username:
            self.add_error(
                'username',
                ValidationError('Esse nome usuario já existe')
            )

        return username


class UserProfileForm(forms.ModelForm):
    phone = forms.CharField(
        required=True,
        min_length=10,
        max_length=15
    )

    picture = forms.ImageField(label='Imagem', required=False)

    class Meta:
        model = UserProfile
        fields = ('phone', 'picture')

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        if not re.match('^[0-9]+$', phone):
            self.add_error(
                'phone',
                ValidationError(
                    'Apenas Números, mínimo de 10 dígitos'
                )
            )

        return phone


class PetRegister(forms.ModelForm):
    class Meta:
        model = Pet
        fields = (
            'name',
            'color',
            'age',
            'age_type',
            'animal_type',
            'available',
        )
        labels = {
            'name': 'Nome',
            'color': 'Cor',
            'age': 'Idade',
            'age_type': 'Dias?',
            'animal_type': 'Tipo de Animal',
            'available': 'Disponível',
        }

pet/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(
        request,
        'global/base.html'
    )

pet/views/pet_views.py
from django.shortcuts import redirect, render
from pet.models import Pet, PetImages, UserProfile
from pet.forms import PetRegister
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def home(request):
    all_pets = Pet.objects.all().order_by('-id')

    pet_list = []
    for pet in all_pets:
        imagem = PetImages.objects.filter(pet_id=pet.id).first()
        pet_list.append((pet, imagem))

    return render(
        request,
        'pet/home.html',
        {
            'pets': pet_list
        }
    )


def pet_details(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    imagens = PetImages.objects.filter(pet_id=pet_id)

    return render(
        request,
        'pet/pet.html',
        {
            'pet': pet,
            'imagens': imagens
        }
    )


def search_type(request, type):
    if type == 'all':
        pets = Pet.objects.all()
    else:
        pets = Pet.objects.filter(animal_type=type)

    pets_list = []
    for pet in pets:
        image = PetImages.objects.filter(pet_id=pet.id).first()
        pets_list.append((pet, image))

    return render(
        request,
        'pet/home.html',
        {'pets': pets_list}
    )


# protected routes
@login_required(login_url='pets:login')
def add_pet(request):
    user = auth.get_user(request)
    form = PetRegister()

    if request.method == 'POST':
        form = PetRegister(request.POST)

        if form.is_valid():
            pet = form.save(commit=False)
            pet.owner_id = user.id
            pet.save()
            files = request.FILES.getlist('images')

            for file in files:
                PetImages(picture=file, pet=pet).save()

        messages.success(request, 'Pet Cadastrado.')

        return redirect('pets:my_pets')

    return render(
        request,
        'pet/add_pet.html',
        {'form': form}
    )


@login_required(login_url='pets:login')
def my_pets(request):
    user = auth.get_user(request)
    pets = Pet.objects.all().filter(owner_id=user.id)

    pets_list = []

    for pet in pets:
        image = PetImages.objects.filter(pet_id=pet.id).first()

        adopter = None
        phone = None
        if pet.adopter_id:
            adopter = User.objects.get(id=pet.adopter_id)
            phone = UserProfile.objects.get(user_id=adopter.id).phone
        pets_list.append((pet, image, adopter, phone))

    return render(
        request,
        'pet/my_pets.html',
        {'pets': pets_list}
    )


@login_required(login_url='pets:login')
def edit_pet(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    form = PetRegister(instance=pet)

    user = auth.get_user(request)
    if user.id != pet.owner_id:
        messages.error(request, 'Esse pet não é seu.')
        return redirect('pets:my_pets')

    if request.method == 'POST':
        form = PetRegister(request.POST, instance=pet)

        if form.is_valid():
            pet = form.save()
            files = request.FILES.getlist('images')

            old_images = PetImages.objects.filter(pet_id=pet.id)
            for old in old_images:
                old.delete()

            for file in files:
                PetImages(picture=file, pet=pet).save()

            messages.success(request, 'Pet Atualizado.')

            return redirect('pets:my_pets')

    return render(
        request,
        'pet/add_pet.html',
        {'form': form}
    )


@login_required(login_url='pets:login')
def delete_pet(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    user = auth.get_user(request)

    if pet.owner_id == user.id:
        pet.delete()
        messages.success(request, 'Pet removido')
    else:
        messages.error(request, 'Voce não pode apagar esse pet.')

    return redirect('pets:my_pets')


@login_required(login_url='pets:login')
def confirm_adoption(request, pet_id):
    user = auth.get_user(request)
    pet = Pet.objects.get(id=pet_id)

    if pet.owner_id != user.id:
        messages.error(request, 'Voce não pode realizar esta ação.')
        return redirect('pets:my_pets')

    pet.available = False
    pet.save()
    messages.success(request, 'Pet adotado')

    return redirect('pets:my_pets')


@login_required(login_url='pets:login')
def refuse_adoption(request, pet_id):
    user = auth.get_user(request)
    pet = Pet.objects.get(id=pet_id)

    if pet.owner_id != user.id:
        messages.error(request, 'Voce não pode realizar essa ação.')
        return redirect('pets:my_pets')

    pet.adopter_id = None
    pet.available = True
    pet.save()
    messages.success(request, 'Adoção recusada.')

    return redirect('pets:my_pets')


@login_required(login_url='pets:login')
def schedule(request, pet_id):
    user = auth.get_user(request)
    pet = Pet.objects.get(id=pet_id)

    if user.id == pet.owner_id:
        messages.error(request, 'Este pet já é seu.')
        return redirect('pets:pet_detail', pet_id)

    pet.adopter_id = user.id
    pet.save()
    messages.success(request, 'Visita agendada.')
    return redirect('pets:my_adoptions')


@login_required(login_url='pets:login')
def my_adoptions(request):
    user = auth.get_user(request)
    pets = Pet.objects.filter(adopter_id=user.id)

    pet_list = []
    for pet in pets:
        image = PetImages.objects.filter(pet_id=pet.id).first()
        owner = User.objects.get(id=pet.owner_id)
        phone = UserProfile.objects.get(user_id=owner.id).phone
        pet_list.append((pet, image, owner, phone))

    return render(
        request,
        'pet/my_adoptions.html',
        {
            'pets': pet_list
        }
    )

pet/views/user_views.py
from email.mime import image
from django.shortcuts import get_object_or_404, redirect, render
from pet.forms import RegisterUser, UserProfileForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth, messages
from pet.models import UserProfile


def register_user(request):
    form = RegisterUser()
    profile = UserProfileForm()

    if request.method == 'POST':
        form = RegisterUser(request.POST)
        profile = UserProfileForm(request.POST, files=request.FILES)

        if form.is_valid() and profile.is_valid():
            user = form.save()
            user_profile = profile.save(commit=False)
            user_profile.user_id = user.id
            user_profile.save()
            messages.success(request, 'Usuário Cadastrado!')

            return redirect('pets:login')

    return render(
        request,
        'pet/user_register.html',
        {
            'form': form,
            'profile': profile
        }
    )


def user_login(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Usuário Logado.')
            return redirect('pets:home')
        messages.error(request, 'Login Invalido')

    return render(
        request,
        'pet/user_login.html',
        {'form': form}
    )


def user_logout(request):
    auth.logout(request)
    messages.success(request, "Logout")
    return redirect('pets:home')


def profile(request):
    user = request.user
    user_form = RegisterUser(instance=user)
    user_profile = UserProfile.objects.get(user_id=user.id)
    profile_form = UserProfileForm(instance=user_profile)
    image = UserProfile.objects.get(user_id=user.id).picture

    if request.method == 'POST':
        user_form = RegisterUser(
            request.POST,
            instance=request.user,
            request=request
        )
        profile_form = UserProfileForm(
            data=request.POST, files=request.FILES, instance=user_profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Usuário atualizado.')

            auth.login(request, user)
            return redirect('pets:my_pets')
        else:
            print(f'ERROS {user_form.errors}')

        return redirect('pets:profile')

    return render(
        request,
        'pet/user_register.html',
        {
            'form': user_form,
            'profile': profile_form,
            'image': image,
            'is_edit': True
        }
    )

pet/templates/pet/add_pet.html
{% extends "global/base.html" %}
{% load static %}
{% block doc_title %}Cadastrar Pet{% endblock doc_title %}

{% block page_css %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock page_css %}

{% block content %}
<div class='form_container'>
    {% include "pet/partials/_pet_form.html" %}
</div>
{% endblock content %}

pet/templates/pet/home.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
    <link rel="stylesheet" href="{% static "css/home.css" %}">
{% endblock page_css %}

{% block doc_title %}Pets{% endblock doc_title %}

{% block content %}
<div class='home_header'>
    <div>
        <h1>Adote um pet</h1>
        <p>Clique em saiba mais para ver mais detalhes do pet.</p>
    </div>
    <div>
        <p>
            Buscar por:
            <a href='{% url "pets:search" "cat" %}'>Gatos</a>
            <a href='{% url "pets:search" "dog" %}'>Cachorros</a>
            <a href='{% url "pets:search" "rabbit" %}'>Coelhos</a>
            <a href='{% url "pets:search" "hamster" %}'>Hamsters</a>
            <a href='{% url "pets:search" "all" %}'>Todos</a>
        </p>
    </div>
</div>
<div class="pet_container">
    {% for pet, imagem in pets %}
        <div class='pet_card'>
            <div class='pet_card_image'>
                {% if imagem.picture %}
                    <img class='pet_card_image' src="{{imagem.picture.url}}" alt="Pet Image">
                {% endif %}
            </div>
            <h3>{{pet.name}}</h3>
            <p>
                <span class='bold'>Idade: </span>
                {{pet.age}} {{pet.get_age_type_display}}
            </p>
            {% if pet.adopter_id %}
                {% if pet.available %}
                    <a class='reserved' href='{% url "pets:pet_detail" pet.id %}'>Adoção em Andamento</a>
                {% else %}
                    <p class='adopted'>Pet Adotado 😊</p>
                {% endif %}
            {% else %}
                <a href='{% url "pets:pet_detail" pet.id %}'>Saiba mais</a>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock content %}

pet/templates/pet/my_adoptions.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
<link rel="stylesheet" href="{% static "css/pets_list.css" %}">
{% endblock page_css %}
{% block doc_title %}Minhas Adoções{% endblock doc_title %}

{% block content %}
<section>
    <div class='petslist_header'>
        <h1>Suas Adoções</h1>
    </div>
    <div class='pet_container'>
        {% if pets %}
            {% for pet, image, owner, phone in pets %}
                <div  class='petlist_row'>
                    <img src="{{image.picture.url}}" alt="{{pet.name}}">
                    <span class='bold'>{{pet.name}}</span>
                        {% if pet.available %}
                            <p>
                                Entre em contato com:
                                <span class='bold'>{{owner.first_name}}</span>
                                <br></br>
                                Telefone:
                                <span class='bold'>{{phone}} </span>
                            </p>
                        {% else %}
                        <div class='actions'>
                            <p>
                                <span class='bold'>Voce já finalizou a adoção desse pet.</span>
                            </p>

                        </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
             <p>Você ainda não adotou nenhum pet.</p>
        {% endif %}
    </div>
</section>
{% endblock content %}

pet/templates/pet/my_pets.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
<link rel="stylesheet" href="{% static "css/pets_list.css" %}">
{% endblock page_css %}
{% block doc_title %}Meus Pets{% endblock doc_title %}

{% block content %}
<section>
    <div class='petslist_header'>
        <h1>Meus pets cadastrados.</h1>
        <a href='{% url "pets:add_pet" %}'>Cadastrar Pet</a>
    </div>
    <div class='pet_container'>
        {% if pets %}
            {% for pet, image, adopter, phone in pets %}
                <div  class='petlist_row'>
                    <img src="{{image.picture.url}}" alt="{{pet.name}}">
                    <span class='bold'>{{pet.name}}</span>
                    {% if adopter %}
                        {% if pet.available %}
                            <p>
                                Visita solicitada por:
                                <span class='bold'>{{adopter.first_name}}</span>
                                <br></br>
                                Telefone:
                                <span class='bold'> {{phone}} </span>
                            </p>
                        {% else %}
                            <p>
                                Adotado por:
                                <span class='bold'>{{adopter.first_name}}</span>
                                <br></br>
                                Telefone:
                                <span class='bold'> {{phone}} </span>
                            </p>
                        {% endif %}
                    {% endif %}
                    <div class='actions'>
                        {% if pet.available %}
                            {% if adopter %}
                                <a class='conclude_btn' href='{% url "pets:confirm_adoption" pet.id %}'>Concluir adoção</a>
                                <a class='refuse_btn' href='{% url "pets:refuse_adoption" pet.id %}'>Recusar adoção</a>
                            {% endif %}
                            <a href='{% url "pets:edit_pet" pet.id %}'>Editar</a>
                            <a href='{% url "pets:delete_pet" pet.id%}'>Excluir</a>
                        {% else %}
                            <p>Pet adotado.</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
             <p>Você ainda não cadastrou nenhum pet.</p>
        {% endif %}
    </div>
</section>
{% endblock content %}

pet/templates/pet/pet.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
<link rel="stylesheet" href="{% static "css/pet.css" %}">
{% endblock page_css %}
{% block doc_title %}{{pet.name}}{% endblock doc_title %}

{% block content %}
<div class="pet_details_container">
    <div class='petdetails_header'>
        <h1>{{pet.name}}</h1>
        <p>Marque uma visita para conhecer o pet. 😊</p>
    </div>
    <div class='pet_images'>
        {% for imagem in imagens %}
            <img src="{{imagem.picture.url}}" alt="{{pet.name}} Image">
        {% endfor %}
    </div>
    <p>
        <span class='bold'>Idade: </span>
        {{pet.age}} {{pet.get_age_type_display}}&nbsp;
        <span class='bold'>Cor: </span>
        {{pet.get_color_display}}
    </p>

    <div class='action'>
        {% if user.is_authenticated %}
            {% if pet.adopter_id %}
                <p class='bold'>Adoção em andamento.
                    <br>Escolha outro pet.
                    <br>Ou aguarde o desenrolar da adoção.</p>
            {% else %}
                <a class='btn-act' href='{% url "pets:schedule" pet.id %}'>Solicitar uma visita.</a>
            {% endif %}
        {% else %}
            <p>
                Você precisa <a href='{% url "pets:register" %}'>criar uma conta</a> para solicitar a visita.
            </p>
        {% endif %}
    </div>
</div>
{% endblock content %}

pet/templates/pet/user_login.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock page_css %}
{% block doc_title %}Login{% endblock doc_title %}

{% block content %}
<div class="form_container">
    <h1>Login</h1>
    <form action="{{form_action}}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-content">
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label_tag}}</label>
                    {{field}}
                    {{field.errors}}
                </div>
            </div>
        {% endfor %}
        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Send</button>
            </div>
        </div>
    </form>

</div>
{% endblock content %}

pet/templates/pet/user_register.html
{% extends "global/base.html" %}
{% load static %}
{% block page_css %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock page_css %}
{% block doc_title %}Cadastrar{% endblock doc_title %}

{% block content %}
<div class="form_container">
    {% if not is_edit %}
        <h1>Cadastrar</h1>
    {% else %}
        <h1>Atualizar</h1>
    {% endif %}
    <div class="profile_image">
        {% if image %}
            <img src="{{image.url}}" alt="User Imagem">
        {% endif %}
    </div>
    {% include "pet/partials/_user_form.html" %}
</div>
{% endblock content %}